name:                camilla
version:             0.1.0.0
github:              "kmein/camilla"
license:             MIT
author:              "Kierán Meinhardt"
maintainer:          "kieran.meinhardt@gmail.com"
copyright:           "Copyright: (c) 2018 Kierán Meinhardt"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Haskell binding to the CMI JSON API (v3) by Technische Alternative GmbH
category:            JSON

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kmein/camilla#readme>

dependencies:
- base >= 4.7 && < 5
- HDBC
- HDBC-sqlite3
- aeson
- aeson-casing
- bytestring
- hashable
- http-client
- iproute
- lens
- text
- time
- time
- unordered-containers
- wreq

library:
  source-dirs: src

executables:
  cmi:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - camilla
    - optparse-applicative

  demo:
    main:                Main.hs
    source-dirs:         demo
    dependencies:
    - camilla
    - ansi-terminal
    - boxes
    - optparse-applicative

tests:
  camilla-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - camilla
    - aeson-qq
    - HUnit
